# Generated by Django 5.1.1 on 2024-09-04 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000000)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
